config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # get 'welcome/index'
  # root 'welcome#index'

  resources :articles
=begin
	get "/articles"            index
	post "/articles"           create
	delete "/articles/:id"     destroy
	get "/articles/:id"        show
	get "/articles/new"        new
	get "/articles/:id/edit"   edit
	patch "/articles/:id"      update
	put "/articles/:id"        update
=end

  root 'welcome#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	# Table
	# Fields
	# Write Methots
  # Validate
  belongs_to :user
  validates :title, presence: true, uniqueness: true
  validates :body, presence: true, length: {minimum: 20}
  # before_create :set_visits_count
  before_save :set_visits_count

  def update_visits_count
    #code
    # self.save if self.visits_count.nil?
    self.update(visits_count: self.visits_count + 1)
  end

  private
  def set_visits_count
    #code
    self.visits_count ||= 0
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :validate_user, except: [:show, :index]
  before_action :authenticate_user!, except: [:show,:index]
  before_action :set_article, except: [:index,:new,:create]

  #GET /articles
	def index
    # All field from Article (SELECT * FROM articles)
		@articles = Article.all
	end
	#GET /articles/:id
	def show
		# @article = Article.find(params[:id])
    @article.update_visits_count
	end

	#GET /articles/new
	def new
    @article = Article.new
	end


  def edit
    # @article = Article.find(params[:id])
  end

  # POST /articles
  def create
    # INSERT INTO
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  # DELETE /articles/:id
  def destroy
    # DELETE FROM  articles

    @article.destroy # Destroy: Delete object from Data Base
    redirect_to articles_path
  end

  # PUT /articles/:id
  def update
    # UPDATE
    # @article.update_attributes({title: 'New Titile'})
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  private
    def set_article
      #code
      @article = Article.find(params[:id])
    end
    def validate_user
      #code
      redirect_to new_user_session_path, notice: "You Need to Start Session"
    end
    def article_params
      params.require(:article).permit(:title,:body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name || "Location"%>
<h1><%= name %> Article</h1>
<%= form_for(@article) do |f| %>
  <% @article.errors.full_messages.each do |message| %>
    <div class="be_red white top_space">
      *<%= message %>
    </div>
  <%end%>

  <div class = "field">
    <%=  f.text_field :title, {placeholder: "Title", class:"form_controls"} %>
  </div>

  <div class="field">
    <%= f.text_area :body, {placeholder: "Write your article", class:"form_controls text_area_form_controls"} %>
  </div>

  <div class="field">
    <%= f.submit "Submit", {class: "form_controls buttom_submit_form_controls"} %>
  </div>
  <%end%>

app/views/articles/edit.html.erb
<!-- <%=  %> -->
<div class="form_container">
  <%= render "form", name: "Edit" %>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
		<div class="">
			<%= article.body %> - <%= link_to "Delete", article, method: :delete, class:"red_Delete"%>
		</div>
<%end%>

app/views/articles/new.html.erb
<!-- <%=  %> -->
<div class="form_container">
  <%= render "form", name: "Create" %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
  <% unless @article.user.nil? %>
    <p>
      Written by: <%= @article.user.email %>
    </p>
    <p>
      Total Visits: <%= @article.visits_count %>
    </p>
  <%end%>
  <div>
    <%= @article.body %>
  </div>
  <div class="">
    <%= link_to "Edit", edit_article_path(@article) %>
  </div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :article_id %>
    <%= form.text_field :article_id, id: :comment_article_id %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= render "partials/navigation"%>
    <%= yield %>
  </body>
</html>

app/views/partials/_navigation.html.erb
<header>
  <nav class="be_red white large_padding">
    <ul class="no-list row center-xs middle-xs">
      <h1 class="no_margin logo">Mawel's Development Blog</h1>
        <li class="col-md li_a">
          <%= link_to "Home", root_path %>
        </li>
        <li class="col-md">
          <%= link_to "Design", root_path %>
        </li>
        <li class="col-md">
          <%= link_to "Programming", root_path %>
        </li>
        <li class="col-md">
          <%= link_to "Technology", root_path %>
        </li>
        <% if user_signed_in? %>
          <li class="col-md">
            <%= link_to "Close Sesion", destroy_user_session_path, method: :delete  %>
          </li>
        <% else %>
          <li class="col-md">
            <%= link_to "Sign_In", new_user_session_path %>
          </li>
          <li class="col-md">
            <%= link_to "Sing_Up", new_user_registration_path %>
          </li>
        <%end%>
    </ul>
  </nav>
</header><!-- /header -->

app/views/welcome/index.html.erb
<% if user_signed_in? %>
<h1>Welcome <%= current_user.email %></h1>
<%end%>